import { Category } from './types';

export const EXPENSE_CATEGORIES: Category[] = [
  { id: 'food', name: 'Food', name_np: 'खाना', emoji: '🍔', color: 'bg-orange-100 text-orange-600' },
  { id: 'transport', name: 'Transport', name_np: 'यातायात', emoji: '🚕', color: 'bg-blue-100 text-blue-600' },
  { id: 'shopping', name: 'Shopping', name_np: 'किनमेल', emoji: '🛍️', color: 'bg-pink-100 text-pink-600' },
  { id: 'bills', name: 'Bills', name_np: 'बिलहरू', emoji: '💡', color: 'bg-yellow-100 text-yellow-600' },
  { id: 'health', name: 'Health', name_np: 'स्वास्थ्य', emoji: '💊', color: 'bg-red-100 text-red-600' },
  { id: 'education', name: 'Education', name_np: 'शिक्षा', emoji: '📚', color: 'bg-indigo-100 text-indigo-600' },
  { id: 'entertainment', name: 'Fun', name_np: 'मनोरंजन', emoji: '🎬', color: 'bg-purple-100 text-purple-600' },
  { id: 'rent', name: 'Rent', name_np: 'भाडा', emoji: '🏠', color: 'bg-teal-100 text-teal-600' },
  { id: 'other', name: 'Other', name_np: 'अन्य', emoji: '📝', color: 'bg-gray-100 text-gray-600' },
];

export const TRANSLATIONS = {
  en: {
    appName: 'Kharcha Bachau',
    home: 'Home',
    log: 'Log',
    history: 'History',
    stats: 'Stats',
    addExpense: 'Add Expense',
    amount: 'Amount',
    category: 'Category',
    description: 'Note',
    save: 'Save',
    cancel: 'Cancel',
    settings: 'Settings',
    toggleLang: 'EN/NP',
    currency: 'Rs.',
    dashboard: 'Dashboard',
    totalToday: 'Expense Today',
    totalSpent: 'Total Spent (This Month)',
    monthlyBudget: 'Monthly Spending',
    vsLastMonth: 'vs Last Month',
    budgetAlert: 'Over Limit',
    budgetGood: 'On Track',
    recent: 'Recent',
    noExpenses: 'No transactions recorded.',
    welcome: 'Welcome',
    login: 'Log In',
    logout: 'Log Out',
    guestRestriction: 'Back up data to cloud',
    searchPlaceholder: 'Search...',
    emptyLog: 'No transactions today',
    edit: 'Edit Transaction',
    update: 'Update',
    delete: 'Delete',
    date: 'Date',
    quickAdd: 'Quick Add',
    expense: 'Expense',
    more: 'More',
    less: 'Less',
    thanLastMonth: 'than last month',
    budgetLimit: 'Monthly Budget Limit',
    analysis: 'Spending Analysis',
    breakdown: 'Category Breakdown',
    today: 'Today',
    yesterday: 'Yesterday',
    pickDate: 'Pick Date',
    wallet: 'Wallet',
    myWallets: 'My Wallets',
    createWallet: 'Create New Wallet',
    personalWallet: 'Personal Wallet',
    walletName: 'Wallet Name',
    create: 'Create',
    addedBy: 'Added by'
  },
  np: {
    appName: 'खर्च बचाउ',
    home: 'गृहपृष्ठ',
    log: 'विवरण',
    history: 'इतिहास',
    stats: 'तथ्याङ्क',
    addExpense: 'खर्च थप्नुहोस्',
    amount: 'रकम',
    category: 'वर्ग',
    description: 'विवरण',
    save: 'सेभ गर्नुहोस्',
    cancel: 'रद्द गर्नुहोस्',
    settings: 'सेटिङहरू',
    toggleLang: 'EN/NP',
    currency: 'रू',
    dashboard: 'ड्यासबोर्ड',
    totalToday: 'आजको खर्च',
    totalSpent: 'कुल खर्च (यो महिना)',
    monthlyBudget: 'मासिक खर्च',
    vsLastMonth: 'गत महिना भन्दा',
    budgetAlert: 'सिमा नाघ्यो',
    budgetGood: 'ठिक छ',
    recent: 'हालैको',
    noExpenses: 'कुनै कारोबार रेकर्ड छैन।',
    welcome: 'स्वागत छ',
    login: 'लग इन',
    logout: 'लग आउट',
    guestRestriction: 'डाटा क्लाउडमा ब्याकअप गर्नुहोस्',
    searchPlaceholder: 'खोज्नुहोस्...',
    emptyLog: 'आज कुनै कारोबार छैन',
    edit: 'सच्याउनुहोस्',
    update: 'अपडेट',
    delete: 'हटाउनुहोस्',
    date: 'मिति',
    quickAdd: 'छिटो थप्नुहोस्',
    expense: 'खर्च',
    more: 'बढी',
    less: 'कम',
    thanLastMonth: '',
    budgetLimit: 'मासिक बजेट सीमा',
    analysis: 'खर्च विश्लेषण',
    breakdown: 'वर्ग अनुसार विवरण',
    today: 'आज',
    yesterday: 'हिजो',
    pickDate: 'मिति छान्नुहोस्',
    wallet: 'वालेट',
    myWallets: 'मेरो वालेटहरू',
    createWallet: 'नयाँ वालेट बनाउनुहोस्',
    personalWallet: 'व्यक्तिगत वालेट',
    walletName: 'वालेटको नाम',
    create: 'बनाउनुहोस्',
    addedBy: 'द्वारा थपिएको'
  }
};