import { Category } from './types';

export const EXPENSE_CATEGORIES: Category[] = [
  { id: 'food', name: 'Food', name_np: 'खाना', emoji: '🍔', color: 'bg-orange-100 text-orange-600' },
  { id: 'transport', name: 'Transport', name_np: 'यातायात', emoji: '🚕', color: 'bg-blue-100 text-blue-600' },
  { id: 'shopping', name: 'Shopping', name_np: 'किनमेल', emoji: '🛍️', color: 'bg-pink-100 text-pink-600' },
  { id: 'bills', name: 'Bills', name_np: 'बिलहरू', emoji: '💡', color: 'bg-yellow-100 text-yellow-600' },
  { id: 'health', name: 'Health', name_np: 'स्वास्थ्य', emoji: '💊', color: 'bg-red-100 text-red-600' },
  { id: 'education', name: 'Education', name_np: 'शिक्षा', emoji: '📚', color: 'bg-indigo-100 text-indigo-600' },
  { id: 'entertainment', name: 'Fun', name_np: 'मनोरंजन', emoji: '🎬', color: 'bg-purple-100 text-purple-600' },
  { id: 'rent', name: 'Rent', name_np: 'भाडा', emoji: '🏠', color: 'bg-teal-100 text-teal-600' },
  { id: 'other', name: 'Other', name_np: 'अन्य', emoji: '📝', color: 'bg-gray-100 text-gray-600' },
];

export const TRANSLATIONS = {
  en: {
    appName: 'Kharcha Bachau',
    home: 'Home',
    log: 'Log',
    history: 'History',
    stats: 'Stats',
    addExpense: 'Add Expense',
    amount: 'Amount',
    category: 'Category',
    description: 'Note',
    save: 'Save',
    cancel: 'Cancel',
    settings: 'Settings',
    toggleLang: 'EN/NP',
    currency: 'Rs.',
    dashboard: 'Dashboard',
    totalToday: 'Expense Today',
    totalSpent: 'Total Spent (This Month)',
    monthlyBudget: 'Monthly Spending',
    vsLastMonth: 'vs Last Month',
    budgetAlert: 'Over Limit',
    budgetGood: 'On Track',
    recent: 'Recent',
    noExpenses: 'No transactions recorded.',
    welcome: 'Welcome',
    login: 'Log In',
    logout: 'Log Out',
    guestRestriction: 'Back up data to cloud',
    searchPlaceholder: 'Search...',
    emptyLog: 'No transactions today',
    edit: 'Edit Transaction',
    update: 'Update',
    delete: 'Delete',
    date: 'Date',
    quickAdd: 'Quick Add',
    expense: 'Expense',
    more: 'More',
    less: 'Less',
    thanLastMonth: 'than last month',
    budgetLimit: 'Monthly Budget Limit',
    analysis: 'Spending Analysis',
    breakdown: 'Category Breakdown',
    today: 'Today',
    yesterday: 'Yesterday',
    pickDate: 'Pick Date',
    wallet: 'Wallet',
    myWallets: 'My Wallets',
    createWallet: 'Create New Wallet',
    personalWallet: 'Personal Wallet',
    walletName: 'Wallet Name',
    create: 'Create',
    addedBy: 'Added by',
    splitExpense: 'Split Expense',
    splitEqually: 'Split equally',
    splitByPercentage: 'Split by percentage',
    customSplit: 'Custom split',
    whoPaid: 'Who paid?',
    selectMembers: 'Select members',
    balanceSummary: 'Balance Summary',
    youOwe: 'You owe',
    owesYou: 'Owes you',
    settle: 'Settle',
    settled: 'Settled',
    yourBalance: 'Your Balance',
    youGetBack: 'You will get back',
    youNeedToPay: 'You need to pay',
    allSettled: 'All settled! No money owed.',
    whoOwesWho: 'Who owes who?',
    owes: 'owes',
    nothingToSettle: 'No money owed between members',
    simpleExplanation: 'When you split expenses, this shows who needs to pay whom.',
    splitWith: 'Split with',
    perPerson: 'per person',
    totalSplit: 'Total split',
    remaining: 'Remaining',
    manageCategories: 'Manage Categories',
    addCategory: 'Add Category',
    editCategory: 'Edit Category',
    deleteCategory: 'Delete Category',
    categoryName: 'Category Name',
    categoryNameNp: 'Category Name (Nepali)',
    categoryEmoji: 'Emoji',
    saveCategory: 'Save Category',
    defaultCategories: 'Default Categories',
    customCategories: 'Custom Categories',
    cannotDelete: 'Cannot delete category that is used in expenses',
    cannotModifyDefault: 'Cannot modify default categories'
  },
  np: {
    appName: 'खर्च बचाउ',
    home: 'गृहपृष्ठ',
    log: 'विवरण',
    history: 'इतिहास',
    stats: 'तथ्याङ्क',
    addExpense: 'खर्च थप्नुहोस्',
    amount: 'रकम',
    category: 'वर्ग',
    description: 'विवरण',
    save: 'सेभ गर्नुहोस्',
    cancel: 'रद्द गर्नुहोस्',
    settings: 'सेटिङहरू',
    toggleLang: 'EN/NP',
    currency: 'रू',
    dashboard: 'ड्यासबोर्ड',
    totalToday: 'आजको खर्च',
    totalSpent: 'कुल खर्च (यो महिना)',
    monthlyBudget: 'मासिक खर्च',
    vsLastMonth: 'गत महिना भन्दा',
    budgetAlert: 'सिमा नाघ्यो',
    budgetGood: 'ठिक छ',
    recent: 'हालैको',
    noExpenses: 'कुनै कारोबार रेकर्ड छैन।',
    welcome: 'स्वागत छ',
    login: 'लग इन',
    logout: 'लग आउट',
    guestRestriction: 'डाटा क्लाउडमा ब्याकअप गर्नुहोस्',
    searchPlaceholder: 'खोज्नुहोस्...',
    emptyLog: 'आज कुनै कारोबार छैन',
    edit: 'सच्याउनुहोस्',
    update: 'अपडेट',
    delete: 'हटाउनुहोस्',
    date: 'मिति',
    quickAdd: 'छिटो थप्नुहोस्',
    expense: 'खर्च',
    more: 'बढी',
    less: 'कम',
    thanLastMonth: '',
    budgetLimit: 'मासिक बजेट सीमा',
    analysis: 'खर्च विश्लेषण',
    breakdown: 'वर्ग अनुसार विवरण',
    today: 'आज',
    yesterday: 'हिजो',
    pickDate: 'मिति छान्नुहोस्',
    wallet: 'वालेट',
    myWallets: 'मेरो वालेटहरू',
    createWallet: 'नयाँ वालेट बनाउनुहोस्',
    personalWallet: 'व्यक्तिगत वालेट',
    walletName: 'वालेटको नाम',
    create: 'बनाउनुहोस्',
    addedBy: 'द्वारा थपिएको',
    splitExpense: 'खर्च बाँड्नुहोस्',
    splitEqually: 'बराबर बाँड्नुहोस्',
    splitByPercentage: 'प्रतिशत अनुसार बाँड्नुहोस्',
    customSplit: 'अनुकूल बाँडफाँड',
    whoPaid: 'कसले तिर्यो?',
    selectMembers: 'सदस्यहरू छान्नुहोस्',
    balanceSummary: 'शेष सारांश',
    youOwe: 'तपाईंले तिर्नुपर्छ',
    owesYou: 'तपाईंलाई तिर्नुपर्छ',
    settle: 'निपटाउनुहोस्',
    settled: 'निपटाइयो',
    yourBalance: 'तपाईंको शेष',
    youGetBack: 'तपाईंले फिर्ता पाउनुहुनेछ',
    youNeedToPay: 'तपाईंले तिर्नुपर्छ',
    allSettled: 'सबै निपटाइयो! कुनै पैसा बाँकी छैन।',
    whoOwesWho: 'कसले कसलाई तिर्नुपर्छ?',
    owes: 'तिर्नुपर्छ',
    nothingToSettle: 'सदस्यहरू बीच कुनै पैसा बाँकी छैन',
    simpleExplanation: 'जब तपाईंले खर्च बाँड्नुहुन्छ, यसले कसले कसलाई तिर्नुपर्छ भनेर देखाउँछ।',
    splitWith: 'सँग बाँड्नुहोस्',
    perPerson: 'प्रति व्यक्ति',
    totalSplit: 'कुल बाँडफाँड',
    remaining: 'बाँकी',
    manageCategories: 'वर्ग व्यवस्थापन',
    addCategory: 'वर्ग थप्नुहोस्',
    editCategory: 'वर्ग सम्पादन गर्नुहोस्',
    deleteCategory: 'वर्ग मेटाउनुहोस्',
    categoryName: 'वर्गको नाम',
    categoryNameNp: 'वर्गको नाम (नेपाली)',
    categoryEmoji: 'इमोजी',
    saveCategory: 'वर्ग सेभ गर्नुहोस्',
    defaultCategories: 'पूर्वनिर्धारित वर्गहरू',
    customCategories: 'अनुकूल वर्गहरू',
    cannotDelete: 'खर्चमा प्रयोग भएको वर्ग मेटाउन सकिँदैन',
    cannotModifyDefault: 'पूर्वनिर्धारित वर्गहरू सम्पादन गर्न सकिँदैन'
  }
};