#!/usr/bin/env bash
# Build the React Native app and ship a release. Run from anywhere.
#
# Release flow: bump expo.version + expo.android.versionCode in mobile/app.json,
# then run this script, then `npm run deploy:hosting` from the repo root.
set -euo pipefail
cd "$(dirname "$0")"   # mobile/

export JAVA_HOME="${JAVA_HOME:-$HOME/.bubblewrap/jdk/amazon-corretto-17.0.20.10.1-linux-x64}"
export ANDROID_HOME="${ANDROID_HOME:-$HOME/.bubblewrap/android-sdk}"
export PATH="$JAVA_HOME/bin:$ANDROID_HOME/platform-tools:$PATH"

# Newest build-tools wins. Pinning a version here meant the signature check below
# silently read nothing and, before the guard was added, shipped regardless.
BT=$(ls -1d "$ANDROID_HOME"/build-tools/*/ 2>/dev/null | sort -V | tail -1)
[ -n "$BT" ] || { echo "ERROR: no Android build-tools found under $ANDROID_HOME" >&2; exit 1; }
APKSIGNER="$BT/apksigner"

# Sync app.json (versionCode/versionName/icons) into the android project.
npx expo prebuild --platform android --no-install

# prebuild clears the android/ directory, which is where the signing material lives
# and which is gitignored. Restore it from mobile/keystore/ (the durable home).
# The signing *config* itself is generated by plugins/withReleaseSigning, so there
# is nothing to patch here.
mkdir -p android/app
cp keystore/release.keystore android/app/release.keystore
cp keystore/keystore.properties android/keystore.properties

[ -f android/app/google-services.json ] || {
  echo "ERROR: android/app/google-services.json is missing." >&2
  echo "       Firebase config is required by the native build. See mobile/.env notes." >&2
  exit 1
}

cd android

# AAB for the Play Store (all ABIs — Play generates per-device downloads).
./gradlew bundleRelease --no-daemon

# APK for direct install at /release/ — arm64 only, covering all modern devices,
# keeps the download ~30 MB instead of ~80 MB.
./gradlew assembleRelease -PreactNativeArchitectures=arm64-v8a --no-daemon

APK=app/build/outputs/apk/release/app-release.apk
AAB=app/build/outputs/bundle/release/app-release.aab

# Refuse to ship a mis-signed artifact. A release build that silently fell back to
# the debug key installs fine on a device and then cannot be updated in place, which
# is only discovered much later. Check the certificate rather than trust the build.
EXPECTED_SHA256=$(keytool -list -v -keystore ../keystore/release.keystore \
  -storepass "$(grep '^storePassword=' ../keystore/keystore.properties | cut -d= -f2)" \
  -alias "$(grep '^keyAlias=' ../keystore/keystore.properties | cut -d= -f2)" 2>/dev/null \
  | grep 'SHA256:' | sed 's/.*SHA256: //; s/://g' | tr '[:upper:]' '[:lower:]')
ACTUAL_SHA256=$("$APKSIGNER" verify --print-certs "$APK" 2>/dev/null \
  | grep -i 'SHA-256 digest' | head -1 | awk '{print $NF}' | tr '[:upper:]' '[:lower:]')

if [ -z "$ACTUAL_SHA256" ]; then
  echo "ERROR: could not read the signing certificate from $APK — not shipping." >&2
  exit 1
fi
if [ "$ACTUAL_SHA256" != "$EXPECTED_SHA256" ]; then
  echo "ERROR: $APK is signed with the wrong key." >&2
  echo "       expected release key $EXPECTED_SHA256" >&2
  echo "       got                $ACTUAL_SHA256" >&2
  echo "       This is a debug-signed build. Not shipping." >&2
  exit 1
fi
echo "Signature verified: $ACTUAL_SHA256"

# Ship: render the download page and publish the artifacts as a GitHub Release.
#
# Artifacts live on GitHub Releases rather than a CDN. The APK is 30 MiB, which is
# past Cloudflare Workers' 25 MiB limit for static assets, and Firebase's Spark plan
# rejects executables outright — and Firebase App Distribution is not a download link
# you can put on a web page. Release assets have no such ceiling and are versioned by
# the release tag, so a download page can be traced to exact source.
#
# Naming: kharcha-bachau-<version>-<short commit>. The commit is in the asset name so a
# file someone is holding is identifiable, and the release tag is the app version, so
# /releases/latest/ always resolves to the newest build.
VERSION=$(node -pe "require('../app.json').expo.version")
SIZE=$(numfmt --to=iec --suffix=B "$(stat -c%s $APK)")
COMMIT=$(git -C .. rev-parse --short HEAD)
DATE=$(date +%d\ %b\ %Y)
REPO=$(git -C .. remote get-url origin | sed -E 's#(git@github.com:|https://github.com/)##; s#\.git$##')
TAG="v$VERSION"
APK_NAME="kharcha-bachau-$VERSION-$COMMIT.apk"
AAB_NAME="kharcha-bachau-$VERSION-$COMMIT.aab"

STAGE=$(mktemp -d)
trap 'rm -rf "$STAGE"' EXIT
cp "$APK" "$STAGE/$APK_NAME"
cp "$AAB" "$STAGE/$AAB_NAME"

NOTES=$(cat <<EOF
Kharcha Bachau v$VERSION — build \`$COMMIT\`.

- APK ($SIZE, arm64) for direct install
- AAB for Play Console upload

Android \`$TAG\` · targetSdk 36 · arm64-v8a, armeabi-v7a, x86, x86_64 in the AAB
EOF
)

if gh release view "$TAG" >/dev/null 2>&1; then
  echo "Release $TAG exists — replacing its assets."
  gh release delete "$TAG" --yes --cleanup-tag
fi
gh release create "$TAG" "$STAGE/$APK_NAME#$APK_NAME" "$STAGE/$AAB_NAME#$AAB_NAME" \
  --repo "$REPO" --title "Kharcha Bachau $TAG" --notes "$NOTES" --target "$COMMIT"

mkdir -p ../public/release
sed -e "s/@@VERSION@@/$VERSION/g" \
    -e "s/@@SIZE@@/$SIZE/g" \
    -e "s/@@SHORTCOMMIT@@/$COMMIT/g" \
    -e "s/@@DATE@@/$DATE/g" \
    ../release-page.html > ../public/release/index.html

echo ""
echo "Release shipped: $TAG ($SIZE) from $COMMIT"
echo "  APK: $APK_NAME"
echo "  AAB: $AAB_NAME  <- upload this to the Play Console"
echo "Next: npm run deploy:hosting  (from the repo root)"
